services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticketify_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MIX_ENV=dev
      - DATABASE_HOST=db
      - DATABASE_URL=ecto://postgres:postgres@db:5432/ticketify_dev
      - PHX_HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    command: >
      sh -c "
        mix deps.get &&
        mix ecto.create &&
        mix ecto.migrate &&
        mix phx.server
      "

volumes:
  postgres_data:
